export const taskDictionary: string[] = [
  "Draw a circle",
  "Make a zigzag",
  "Reach top left corner",
  "Touch all 4 edges",
  "Make a spiral",
  "Do the worm",
  "cough",
  "Observing the target before approaching it",
  "Like going against strong wind",
  "Navigating through a maze",
  "Climbing a steep hill",
  "Like crossing a river",
  "Following a breadcrumb trail",
  "Like sailing against the tide",
  "Walking a tightrope",
  "Like running a marathon",
  "Like planting seeds and waiting to grow",
  "Like navigating a storm",
  "Like climbing a ladder",
  "Like threading a needle",
  "Like following a map",
  "Like breaking through a wall",
  "Like chasing shadows",
  "Like building a bridge",
  "Like running through a field of obstacles",
  "Like navigating a ship through fog",
  "Like climbing a mountain",
  "Like crossing a desert",
  "Like following a river",
  "Like riding a rollercoaster",
  "Like forging a path through the wilderness",
  "Like dancing through a storm",
  "Like planting a flag",
  "Like navigating a labyrinth",
  "Like scaling a wall",
  "Like walking on a path of fire",
  "Like swimming upstream",
  "Like following a compass",
  "Like riding a bicycle uphill",
  "Like crossing a bridge",
  "Like searching for a needle in a haystack",
  "Like navigating a minefield",
  "Like climbing a tree",
  "Like walking through a fog",
  "Like following a star",
  "Like breaking the ice",
  "Like running a race",
  "Like weaving a tapestry",
  "Like following a trail of breadcrumbs",
  "Like navigating a ship through rough seas",
  "Like climbing a staircase",
  "Like crossing a finish line",
  "Like planting roots",
  "Like riding the waves",
  "Like following a path in the woods",
  "Like walking through a door",
  "Like lighting a candle",
  "Like navigating a crowded street",
  "Like climbing a mountain peak",
];

// around 40-60 "prompts" of metaphors (like "in a marching band"). This will be like a database or dictionary.
// When the user chooses small, medium, or large, this choice will determine how many prompts are pulled from the dictionary.
// These pulled prompts will be packaged as a small list for them (temporary for that user) in some way that is efficient, and given to the user via the current process, but instead of a loaded in csv that the operator must initialize, it will be automatically processed and started by the user selecting a size.
